services:
  - type: web
    name: lead-analytics-backend
    env: python
    buildCommand: pip install -r requirement.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production

